### ISSUE TITLE
error 017: undefined symbol "g_eMenuModelData"

### ISSUE THREAD

**Issue by imTurv** [TommyB123/eSelection#1]
Hi, I just downloaded the latest version of eSelection and I have a problem with the include

When I compile adding the #include <eSelection> I get these errors

pawno\include\eSelection.inc(46) : error 001: expected token: "-identifier-", but found "enum"
pawno\include\eSelection.inc(185) : error 017: undefined symbol "g_eMenuModelData"
pawno\include\eSelection.inc(185) : error 009: invalid array size (negative, zero or out of bounds)
pawno\include\eSelection.inc(185) : error 001: expected token: ")", but found ";"
pawno\include\eSelection.inc(185) : fatal error 107: too many error messages on one line

Thanks so much for reading

**Comment by TommyB123** [comment]
This should be fixed in the latest release. Please try again and let me know if it works.

**Comment by imTurv** [comment]
No, I still have the same error lines

**Comment by TommyB123** [comment]
It works fine for me. Do you use sampctl? You'll probably need to run `sampctl p ensure` on your project if you do.

**Comment by Zeex-X** [comment]
error 017: undefined symbol
